version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "xet7"
    assignees
      - "xet7"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "xet7"
    assignees:
      - "xet7"
